---
- name: "Copy backend tar.gz"
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "installing dependencies"
  become: yes
  npm:
    path: /home/ubuntu/backend
    
# - name: "Stop default pm2"
#   become: yes
#   shell: pm2 stop default
#   args:
#     chdir: /home/ubuntu/backend

- name: "start pm2"
  become: yes
  shell: pm2 start --name "backend" npm -- start
  args:
    chdir: /home/ubuntu/backend